<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ApiService.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="3dcac768.0" />
    <None Remove="c8750f0d.0" />
    <None Remove="rootCert.pfx" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="3dcac768.0" />
    <EmbeddedResource Include="c8750f0d.0" />
    <EmbeddedResource Include="rootCert.pfx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    <PackageReference Include="Titanium.Web.Proxy" Version="3.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MainUi.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>